language: python
python:
  - "3.5"
before_install:
  - pip install --upgrade pip
  - pip install pipenv
install:
  - pipenv install --dev --deploy
  - pipenv install codecov
after_success:
  - pipenv run codecov
